### PR TITLE
Add correct indentation for 'with' keyword

### PR DESCRIPTION
**Pull request by tonini**
```elixir
defmodule Foo do

  def bar do
    with {:ok, width} <- Map.fetch(opts, :width),
      {:ok, height} <- Map.fetch(opts, :height) do
      {:ok, width * height}
    else
      :error ->
        {:error, :wrong_data}
    end
  end
  
  def bar do
    with {:ok, width} <- Map.fetch(opts, :width),
      {:ok, height} <- Map.fetch(opts, :height),
      do: {:ok, width * height},
      else: {:error, :wrong_data}

    with({:ok, width} <- Map.fetch(opts, :width),
      {:ok, height} <- Map.fetch(opts, :height),
      do: {:ok, width * height},
      else: {:error, :wrong_data})    
  end
end
```

### CODE REVIEW

**Comment by whatyouhide** [comment]
@tonini I don't think we should adopt the indentation you're using in the `bar/0` function there. [The documentation for the `with` special form](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/special_forms.ex#L1377-L1380) indents `with` as like this:

```elixir
with pattern <- foo(),
     other_pattern <- bar(),
     last_pattern <- baz(),
  do: bong()
```

I really like this indentation since all the patterns are aligned, and the `:do` action is indented just one level over the `with`. By indenting `with` as:

```elixir
    with {:ok, width} <- Map.fetch(opts, :width),
      {:ok, height} <- Map.fetch(opts, :height),
      do: {:ok, width * height},
      else: {:error, :wrong_data}
```

It's really easy to mix up the patterns and the `do`/`else` actions. Wdyt?

**Comment by christopheradams** [comment]
```elixir
      do: {:ok, width * height},
      else: {:error, :wrong_data}
```

@tonini @whatyouhide since these lines won't compile, I'm curious what the second example was meant to look like.

**Comment by whatyouhide** [comment]
@christopheradams it was meant to show a "bad" indentation anyways, so it's not really relevant that the `:else` be there :)

IMO, good indentations are:

```elixir
with pattern <- foo(),
     other_pattern <- bar(),
     last_pattern <- baz(),
  do: bong()
```

and

```elixir
with pattern <- foo(),
     other_pattern <- bar(),
     last_pattern <- baz() do
  hello()
else
  else_pattern ->
    else_action()
```

**Comment by christopheradams** [comment]
Thanks for the update @whatyouhide. I've gathered this is the preferred style based on what has been discussed here and implemented in elixir-mode.

I'm looking to add this rule to the Elixir Style Guide, and I'd be grateful for your feedback on [this issue](https://github.com/christopheradams/elixir_style_guide/issues/101#issuecomment-264699279)

**Comment by whatyouhide** [comment]
What you say in that issue makes sense to me @christopheradams, if you need my personal endorsement for this style you can link to this issue 😄

**Comment by lexmag** [comment]
@christopheradams second example should look like this:
```elixir
do: {:ok, width * height},
else: (:error -> {:error, :wrong_data})
```

**Comment by whatyouhide** [comment]
Small note: while @lexmag is right, personally I think if you have `:else` it's better to use the multiline syntax.

**Comment by lexmag** [comment]
I think I must to mention that:

```elixir
with pattern <- foo(),
     other_pattern <- bar(),
     last_pattern <- baz(),
  do: bong()
```
indentation didn't "survive" in Elixir code, when I was developing `with/1` feature I tried to bring this indentation, and so started with docs, but it was never used after in new code.
Today I even think it looks awkward and less intuitive as `do:` is effectively just another argument and is not something special. :bowtie:
So together with @whatyouhide we agreed to change `with/1` style in [lexmag/elixir-style-guide](https://github.com/lexmag/elixir-style-guide#with-indentation) and also fix indentation [Elixir examples](https://github.com/elixir-lang/elixir/commit/345ce9c5929106dbde3431b839a60d9971bc236c).

CC @christopheradams

**Comment by christopheradams** [comment]
@lexmag it looks like the general rule from your links is that any `do:` or `else:` should be indented the same as the previous line. However, the `do` and `else` examples haven't changed (where a `do` goes on the end of the line, and the following line is indented normally; and `else` always goes on a line by itself).

I think that makes sense.

Part of me wishes we could avoid these special indentation/alignment rules that have to match the width of the preceding special form or macro (like `with`, `defstruct`, `for`, etc.). For example, I find [this rule][1] much wiser than [this one][2].

[1]: https://github.com/lexmag/elixir-style-guide#multi-line-expr-assignment
[2]: https://github.com/lexmag/elixir-style-guide#guard-clauses

**Pull request closed without merging**
