### PR TITLE
Correct pipeline indentation

### LINKED ISSUE #243: Correct indentation for pipe operator
The [elixir style guide](https://github.com/niftyn8/elixir_style_guide) recommends this:

```elixir
# Multiline pipelines use a single level of indentation.
some_string
|> String.downcase
|> String.strip

# Multiline pipelines on the right side of a pattern match
# should be indented on a newline
sanitized_string =
  some_string
  |> String.downcase
  |> String.strip
```

emacs-elixir will indent the second example as:

```elixir
sanitized_string =
  some_string
|> String.downcase
|> String.strip
```

It would be nice if support for the elixir style guide format could be added. Thanks :)

### PR DESCRIPTION
**Pull request by tonini**
fixes #243

### CODE REVIEW

**Comment by whatyouhide** [comment]
Awesome :clap:!

**Comment by gausby** [comment]
I appreciate this, thanks!

**Comment by tonini** [comment]
Thanks I appreciate the patience you guys had :smile:

**Comment by gausby** [comment]
Hmm, I don't think this is solved completely. Just pulled the master of emacs-elixir and got this behavior:

I expected this:
```elixir
defmodule Foo do
  def bar do
    baz =
      [1,2,3,4,5,6,7,8,9]
      |> Enum.reverse
      |> Enum.filter(&(&1 > 5))
  end
end
```
I got this:
```elixir
defmodule Foo do
  def bar do
    baz =
      [1,2,3,4,5,6,7,8,9]
          |> Enum.reverse
              |> Enum.filter(&(&1 > 5))
  end
end
```
Is it just me?

**Comment by tonini** [comment]
thanks @gausby!

I'm on it

**Comment by whatyouhide** [comment]
Reproduced the same behaviour as @gausby.

**Comment by mreyk** [comment]
Hi everyone, I just wanted to know if this is solved or not. A similar issue happens with the `case do`. Elixir indentation should be this one:
```
variable
|> case do
  nil ->
    :noop
  _ ->
    :ok
end
```

But the elixir-mode does this, it places four spaces:
```
variable
|> case do
    nil ->
      :noop
    _ ->
      :ok
end
```

**Comment by axelson** [comment]
@mreyk can you file that as a separate issue?

**Pull request merged**
