### PR TITLE
True,false, nil are highlighted as atoms

### PR DESCRIPTION
**Pull request by edmz**

### CODE REVIEW

**Comment by mattdeboard** [comment]
:+1: for including tests

**Comment by edmz** [comment]
to be honest, @tonini made me do it :P

I had to understand how they worked

**Comment by mattdeboard** [comment]
Well then I revoke my :+1: and award it to @tonini

**Comment by mattdeboard** [comment]
May God have mercy on your soul

**Comment by tonini** [comment]
:laughing:

**Pull request merged**
