### PR TITLE
remove do keyword to handle also oneline definitions

### PR DESCRIPTION
**Pull request by tonini**

### CODE REVIEW

**Comment by mattdeboard** [comment]
What does this fix?

**Comment by tonini** [comment]
The following will also be identified as a symbol

```elixir
@doc false
defmacro __before_compile__(env) do
  plugs = Module.get_attribute(env.module, :plugs)
  {conn, body} = Plug.Builder.compile(env, plugs, [])

  quote do
>   defp phoenix_endpoint_pipeline(unquote(conn)), do: unquote(body)
  end
end
```

```elixir
def broadcast(_, _, _, _, _), do: raise_invalid_message
```

And also functions with `!` and `?`

```elixir
 def broadcast!(_, _, _, _), do: raise_invalid_message
 def broadcast?(_, _, _, _), do: raise_invalid_message
```

So now it wouldn't matter if it's a one-line definition or not and also the `!` / `?` will be handeled.

**Comment by mattdeboard** [comment]
So does this fix #212?

**Comment by tonini** [comment]
Unfortunately no, it have nothing to do with the indentation.

**Comment by mattdeboard** [comment]
I understand.

**Comment by mattdeboard** [comment]
Once travis clears I'll merge it

**Comment by tonini** [comment]
:+1: :heart:

**Pull request merged**
